#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy       -> @derfredy:matrix.org     #
#  @Bitcoinera -> @bitcoinera:matrix.org       #
#  @Tropicar                                   #
################################################

key_name=$(sentinel-hub-cli keys list | awk 'FNR==1{print $3}')
chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
cosmosvaloper=$(sentinel-hub-cli keys show $key_name --bech=val | awk 'FNR==3{print $2}')

sentinel-hub-cli query staking validator $cosmosvaloper --chain-id=$chain_id --output=json | jq '.jailed'

